### ISSUE TITLE
When encoding U+301C to legacy Japanese encodings, consider encoding as U+FF5E

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#114]
uconv encoded U+301C as U+FF5E. Chromium does not, at least in the ISO-2022-JP case. Can't test Edge and IE right now, because software.hixie.ch is down.

I'm not saying we should do this, but let's at least give this multi-person evaluation.

**Comment by jungshik** [comment]
It would make sense only if dominant Japanese IMEs on Windows and Mac produce different characters when ~ is pressed in the full width mode. (E.g. 301C on Windows and F5 on Mac)

Btw, Chrome doesn't have that fallback encoding because the current spec doesn't.

**Comment by hsivonen** [comment]
I don't see Edge doing this for ISO-2022-JP.

**Comment by annevk** [comment]
I cannot see this behavior when I run `encoding/legacy-mb-japanese/euc-jp/eucjp-encode-form-cseucpkdfmtjapanese.html` in each browser. Same for `encoding/legacy-mb-japanese/shift_jis/sjis-encode-form-csshiftjis.html`. For some reason I cannot get the ISO-2022-JP test to run.

I think we can close this?

**Comment by hsivonen** [comment]
Let's close this.

**Comment by annevk** [comment]
FWIW, the ISO-2022-JP test had a bug that I fixed in https://github.com/w3c/web-platform-tests/commit/b6fc6d7b9d4d4ef015d0345adcc0ba4403f6e03b, but that didn't change the outcome for this issue.
