### ISSUE TITLE
Signaling EOF in the streaming case is unspecified (or too unclear)

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#12]
AFAICT, Gecko's `TextDecoder` doesn't handle EOF at all in the streaming mode. When I look at the spec, it's not clear to me how EOF is supposed to be signaled in the API. By passing `null` as the input to `decode()` maybe?

**Comment by inexorabletash** [comment]
Just `decode()`. An example using streaming would probably help. e.g. from https://github.com/inexorabletash/text-encoding

```js
var string = "", decoder = TextDecoder(encoding), buffer;
  while (buffer = next_chunk()) {
    string += decoder.decode(buffer, {stream:true});
  }
  string += decoder.decode(); // finish the stream
```

**Comment by hsivonen** [comment]
OK. The spec algorithm for `decode()` is very far from making this clear.

**Comment by annevk** [comment]
Note that per the specification you signal EOF by a call to `decode()` that does not have the `stream` member set to true. You can still pass in additional input at that point. At what point does the algorithm confuse you?

**Comment by annevk** [comment]
Would the confusion be removed once we make the change I suggested in #13?

**Comment by hsivonen** [comment]
The definition of the flags is separate from the algorithm, so it's easy to get confused by thinking that the *streaming flag* is an algorithm-local variable (as opposed to being a field of the object), since the corresponding JS argument is to the `decode` method and not to the constructor.

Other than that, I guess the general problem is that the last two top-level steps of the algorithm require examining the implications of the definitions they reference and, thus, the algorithm isn't obvious when taking a look without reading all the definitions and thinking through their implications. 

The change suggested in #13 would alleviate the confusion. To remove confusion completely, substep 2 of major step 5 could use an informative note that points out that streamability is based on omitting EOF handling in that step and leaving flags such that the step 1 is skipped on the next call.

**Comment by hsivonen** [comment]
Oh, and for authors, it would be helpful to have a usage note that says in the streaming case you call `decode` 0 to N times with `{stream:true}` and then once without and if you don't have input for that last call, you should just omit both arguments.

**Comment by annevk** [comment]
Thank you for the clear suggestions @hsivonen! @inexorabletash, I ended up using your example too.
