### ISSUE TITLE
Need more changes for common deploy

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#126]
https://github.com/whatwg/encoding/commit/f381389b0addceb96c16dd2602a84d82ab7a2390 missed out on some details other such changes, e.g., https://github.com/whatwg/fetch/commit/948505d35344cd99599f52458ad8898e99ce2afc, did include. Makefile, README.md, .gitignore changes.

cc @foolip

**Comment by foolip** [comment]
Makefile didn't have a deploy target to begin with, so no changes were needed there. README.md is wrong now though, that's true.

**Comment by annevk** [comment]
Well, as you can see in the Fetch PR I added the deploy target.

**Comment by foolip** [comment]
Yes, that would make the README.md nicer.

**Comment by annevk** [comment]
This was fixed in d55cb85655eab662da03e3552275c035f1d91daa.
