### ISSUE TITLE
Figure out if anything is needed for better HTML integration

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#128]
@hsivonen in https://github.com/whatwg/html/issues/1077#issuecomment-214780498 raised a number of issues with the current integration points. They are insufficient for CSS, HTML, and presumably XML.

This might require some substantive changes to the hooks and perhaps other parts of the Encoding Standard, as well as standards that depend on the Encoding Standard (of which there are quite a few, so tread carefully).

Belated filing this to keep better track of it.

**Comment by annevk** [comment]
I think I'd personally be okay if the standard just said that you had to wait for 1024 bytes before decoding and if you could optimize around that, it would be okay too. The difference should only be observable performance-wise, which seems acceptable. And we can encourage implementations to do the fast thing.

I think that remains true if we add encoding sniffing.

Rewriting the specifications to have the proper abstractions would be somewhat nicer obviously, but seems like a lot more effort.

Note that we still have to change "decode" to also return the chosen encoding to the caller (and adjust any callers as appropriate).

**Comment by andreubotella** [comment]
I'm reopening the discussion about this feature in https://github.com/whatwg/html/issues/1077#issuecomment-596593415
