### ISSUE TITLE
Streaming should be a flag on the decoder instead of being a flag on the decode() call

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#13]
Making the streaming mode a flag on the `decode()` call is rather strange API design. In Gecko's implementation, performing a streaming `decode()`, followed by a non-streaming `decode()` followed by a streaming `decode()` yields potentially surprising results. I don't blame the Gecko implementation: it's weird API design that the API makes this possible.

I'd have expected the streaming mode to be a flag on the `TextDecoder` object set at the time of instantiation--i.e. a flag passed to the constructor. Is there a chance to make it so without breaking the Web at this point? If not, the spec could use some text explicitly calling out this oddity and explaining its implications.

**Comment by inexorabletash** [comment]
As an aside, `doNotFlush` would have captured the intended semantics of the flag more clearly, but design by committee happened.

**Comment by hsivonen** [comment]
Wow, saying it's `doNotFlush` makes so much more sense than `stream`. Having the spec use "do not flush" as the conceptual flag and then say that for the flag spelled as `stream` is meant to mean "do not flush" would be a huge improvement already.

In the Gecko case, a code change is still necessary: The current Gecko behavior doesn't allow you to flush state left around by `stream` by making a subsequent call without `stream`.

Another observation: I expect users of the API who think the non-`stream` calls are stateless to be surprised by the BOM-related state surviving a non-`stream` call to `decode()`.

**Comment by annevk** [comment]
@hsivonen so your suggestion is to rename "streaming flag" to "do not flush flag"? That seems fine to me.

**Comment by hsivonen** [comment]
> so your suggestion is to rename "streaming flag" to "do not flush flag"?

Yes. Without changing the actual API, that's the single best way to make things more comprehensible.

**Comment by annevk** [comment]
Thank you!
