### ISSUE TITLE
Identity encoding?

### ISSUE THREAD

**Issue by zb3** [whatwg/encoding#138]
I realize this is probably a wrong place to ask this, but are/were there any plans to add some kind of "identity" encoding? Such that for each x in range `[0, 255]`, these would be true:
```javascript
new TextDecoder(SOMETHING).decode(new Uint8Array([x])).charCodeAt(0) === x
new TextEncoder(SOMETHING).encode(String.fromCharCode(x))[0] === x
```

I am asking because I'd normally expect the `iso-8859-1` encoding to work this way, but it maps to `windows-1252` even though they're not the same...
I've checked all available encodings but found none that has above properties.

This could greatly simplify conversion between `Uint8Array` and Base64 using `atob`/`btoa` (of course a `base64` encoding would simplify it even more...)

**Comment by annevk** [comment]
We basically don't want to expand what we consider "text" so supporting these through `TextDecoder` and `TextEncoder` is unlikely to happen.

FWIW, https://infra.spec.whatwg.org/#isomorphic-decode and https://infra.spec.whatwg.org/#isomorphic-encode are those operations within the web platform, but they don't have an exposed API.

We've had requests for `base64` (and maybe `base64url`, don't quite remember) too, but no proposal came forward.

There's also a proposal for gzip streaming, tracked at https://github.com/whatwg/fetch/issues/653.

Perhaps these "non-text" things should form their own set of APIs.

**Comment by annevk** [comment]
I'm going to close this since we won't add them as part of the Encoding Standard. If there continues to be demand we should consider exposing isomorphic decode/encode somehow.

**Comment by inexorabletash** [comment]
> We've had requests for base64 (and maybe base64url, don't quite remember) too, but no proposal came forward.

One problem is that the semantics are reversed (_encoding_ text to binary is _decoding_ base64 to binary, and _decoding_ binary to text is _encoding_ binary to base64).

+1 to new APIs per the fetch bug. This is something we (Chromium folks) hope to look at in the medium term.
