### ISSUE TITLE
Allow conformant implementations to support non-UTF-8 encodings 

### ISSUE THREAD

**Issue by eyalroz** [whatwg/encoding#144]
There seems to be some work/issues open regarding support for additional charset encodings (e.g. #62). However, at the moment, the spec requires that _nothing_ other than UTF-8 be supported, even if a browser/application/JS engine can support it experimentally/as an extension. This has made Mozilla (among others?) drop support for multiple character set encodings - which is important for various extensions (e.g. my own Thunderbird extension). 

It would this be useful if, while various encodings are considered for mandatory support, that they (or, in fact, any) encoding be supported on a voluntary basis.

**Comment by annevk** [comment]
#62 is about tests and tracking implementation status of that encoding. It's not entirely clear what this issue is after as non-UTF-8 encodings are supported. Are you talking about encoder support in the API?

**Comment by hsivonen** [comment]
The Encoding Standard seeks to be normative over Web browsers. In the context of Web browsers, it would be bad to suggest that browsers can support other encodings, because that would result in Web content that's browsable in some browsers but not others. Importantly, additional encodings don't add any expressiveness to platform over UTF-8 anyway, since everything decodes to Unicode.

It's already understood that despite an occasional email-motivated tiny spec change (such as the addition on the "ms932" label), the Encoding Standard is insufficient for email clients. Specifically, experience suggests that an email client needs to support one additional decoder: for UTF-7. Yet, we _really_ don't want UTF-7 in the Web Platform.

Thunderbird already supports UTF-7 decoding outside the framework that Gecko provides for Web content.

Now that Gmail and Apple Mail always send email as UTF-8 and have done so for a while, recipients just have to be able to deal with it. As a result, sending non-UTF-8 email doesn't make sense for other email clients and I encourage Thunderbird to get rid of the capability to send non-UTF-8 email.

What does your extension try to do and why?

**Comment by eyalroz** [comment]
Yes, I'm talking about how "UTF-8-only" is currently baked into the encoding API:

Section [7.2 ](https://encoding.spec.whatwg.org/#interface-textdecoder )for example:
>  TextEncoder object offers no label argument as it only supports UTF-8. It also offers no stream option as no encoder requires buffering of scalar values. 
...
>
```
encoder . encoding
    Returns "utf-8".```

**Comment by eyalroz** [comment]
> The Encoding Standard seeks to be normative over Web browsers. In the context of Web browsers, it would be bad to suggest that browsers can support other encodings, because that would result in Web content that's browsable in some browsers but not others. Importantly, additional encodings don't add any expressiveness to platform over UTF-8 anyway, since everything decodes to Unicode.

The suggestion that huge parts of the web, which were created (in "good faith") using non-UTF-8 charset encoding, and continue to be created that way, should be made non-browsable so as to make browser behavior uniform, seems bizarre and, frankly, somewhat offensive.  (And that's doubly the case considering how additional charset encodings are to be added in the future anyway.)

**Comment by annevk** [comment]
> The suggestion that huge parts of the web, which were created (in "good faith") using non-UTF-8 charset encoding, and continue to be created that way, should be made non-browsable so as to make browser behavior uniform, seems bizarre and, frankly, somewhat offensive.

I think there's a misunderstanding. The Encoding Standard both defines non-UTF-8 encodings and requires them to be supported. So such legacy content will continue to function just fine.

> And that's doubly the case considering how additional charset encodings are to be added in the future anyway.

What makes you say this?

It'd greatly help if you could separate your concerns clearly, as the API is really somewhat separate from all this and has its own design considerations.

**Comment by hsivonen** [comment]
>> The Encoding Standard seeks to be normative over Web browsers. In the context of Web browsers, it would be bad to suggest that browsers can support other encodings, because that would result in Web content that's browsable in some browsers but not others. Importantly, additional encodings don't add any expressiveness to platform over UTF-8 anyway, since everything decodes to Unicode.
>
> The suggestion that huge parts of the web, which were created (in "good faith") using non-UTF-8 charset encoding, and continue to be created that way, should be made non-browsable so as to make browser behavior uniform, seems bizarre and, frankly, somewhat offensive. (And that's doubly the case considering how additional charset encodings are to be added in the future anyway.)

To be clear, in the text you quoted from me "other encodings" means encodings other than the ones defined in the Encoding Standard, i.e. I was responding to your suggestion of "voluntarily" supporting even more encodings. I didn't mean "other encodings" in the sense of encodings other than UTF-8. The purpose of defining non-UTF-8 encodings in the Encoding Standard is to keep legacy Web content working.

As for `TextEncoder`, it's not a legacy API. It's a new API. It's not the purpose of the Encoding Standard to facilitate the creation of new non-UTF-8 data.

So if you are implementing an email client in JS, `TextDecoder` gives you consumption everything except UTF-7, which you need to implement yourself. `TextEncoder` gives you emission of UTF-8. It's not a good idea to _send_ email in non-UTF-8 encodings these days even if it's necessary to be able to _receive_ non-UTF-8 emails.

**Comment by SHwareSystemsDev** [comment]
2 points to consider:

1) UTF8 is registered as an alternate encoding model that supports standard return to other ISO-IR encoding model charsets.  So it appears Unicode already requires these ALL still be supported for decoding web server sourced content, and encoding when a browser is saving decoded text extracted from this web content locally. In China it's required encoding to GB-18030 be supported also for such saves. While a variety of C0 sets can be mapped into the /x00 to /x1F code space, all the registered ones support ESC as the current edition of ISO-2022 requires, which includes that standard return sequence. 

2) At the time UCS4 replaced UCS2 as the encoding model for Unicode it was known this range might also be inadequate for future purposes and then Unicode would be obsolete. It was hoped this inadequacy would be evident later than sooner so went ahead anyways with the change. However, some recent websites, some with millions of users, have provided facilities for creating, and usage in text, of what are, logically, user-defined emoji or CJK Han-type glyph code points, with the net result that time is NOW. Sure, it will twitch about for a few more years in its death throes, but it is terminal. Eventually people will start proposing these as extensions to their script's lexicon and if Unicode doesn't assign them a code point for interchange, some other registry will be created that will and probably subsume all of what Unicode has done so far.

So, to me betting all your money on Unicode being the encoding of choice for future web browsers is a non-starter. For similar reasons GB-18030 is not in the race either. ISO-2022 has its own versions of myopia, but range isn't one of them so it's still in the running; a 4-byte 94-n encoding has 70+ times the range of code points UCS4 supports. There may be a UCS6 or UCS8, but I wouldn't expect these to be backwards compatible. Some other candidates still under development may also emerge from the bowels of Adobe's or IBM's development labs, or other company, too.

**Comment by annevk** [comment]
Well, we already bet all our money on Unicode long ago. I'm going to close this since I don't think there's anything actionable here.
