### ISSUE TITLE
TextDecoder's serialize stream algorithm seems unnecessarily convoluted.

### ISSUE THREAD

**Issue by Codifier** [whatwg/encoding#154]
It appears to me that some algorithms are unnecessarily convoluted. One in particular is the [TextDecoder's serialize stream algorithm](https://encoding.spec.whatwg.org/commit-snapshots/6f9a41f3d9dbc7ba6d88f65f7ef1c139fb08d4be/#concept-td-serialize):

> 1. Let output be the empty string.
> 2. While true:
>    1. Let token be the result of reading from stream.
>    2. If encoding is UTF-8, UTF-16BE, or UTF-16LE, and ignore BOM flag and BOM seen flag are unset, then:
>       1. If token is U+FEFF, then set BOM seen flag.
>       2. Otherwise, if token is not end-of-stream, then set BOM seen flag and append token to output.
>       3. Otherwise, return output.
>    3. Otherwise, if token is not end-of-stream, then append token to output.
>    4. Otherwise, return output.

Unless I'm mistaken, I believe it could be simplified to:

> 1. Let output be the empty string.
> 2. While true:
>    1. Let token be the result of reading from stream.
>    2. If token is end-of-stream, return output.
>    3. If encoding is UTF-8, UTF-16BE, or UTF-16LE, and ignore BOM flag and BOM seen flag are unset, then:
>       1. Set BOM seen flag.
>       2. If token is U+FEFF, then continue.
>    4. Append token to output.

...because the "BOM seen flag" will only ever be set if the token is *not* "end-of-stream".

**Comment by ricea** [comment]
This simplification appears to be correct to me. I'd like some other people to double-check it.

It's also quite close to what Blink actually implements, but since Blink's implementation is layered differently, there isn't a direct 1:1 mapping.

**Comment by annevk** [comment]
I looked at blame and the original algorithm is 5 years old. I'm pretty sure that was before we standardized on "continue" on Infra, so perhaps that explains the way it is. In any event, rewriting it seems acceptable.

@Codifier how would you like to be acknowledged?

**Comment by Codifier** [comment]
@annevk You can mention me as CodifierNL in any acknowledgement you deem appropriate. Thank you.

**Comment by is2ei** [comment]
@annevk 
Anyone works on this issue? If not, I'd like to work on this.

**Comment by annevk** [comment]
@is2ei please do!
