### ISSUE TITLE
bind encoder to self

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/encoding#159]
This is a minor issue, but i think it's a more convenient to pass the `encode` into functions and use the same encoder thought out a serie of task. Instead of creating new instances or small anonymous function `.then(str => encoder.encode(str))`. A simple fix would be something like 
`let encode = new TextEncoder(); encode = encode.encode.bind(encode)`

```js
somePromise
  .then(new TextEncoder().encode)
  .then(console.log)
```

now it just throws `TypeError: Illegal invocation`

**Comment by annevk** [comment]
I don't really understand the usage pattern. Note that the encoder object is important for preserving state, you cannot ignore it.

**Comment by ricea** [comment]
Does
```javascript
const encode = TextEncoder.prototype.encode.bind(new TextEncoder());
```
do what you want?

**Comment by annevk** [comment]
I'm going to close this given the lack of feedback from OP. Happy to reopen once we have more information.

**Comment by jimmywarting** [comment]
> Does
> 
>  ```js
> const encode = TextEncoder.prototype.encode.bind(new TextEncoder());
> ```
> do what you want?

yes
