### ISSUE TITLE
iso-2022-jp decoder, "trail byte" case says to prepend byte in the end of stream step

### ISSUE THREAD

**Issue by mrmixer** [whatwg/encoding#164]
In the [iso-2022-jp decoder](https://encoding.spec.whatwg.org/#iso-2022-jp-decoder), in the "trail byte" case, when byte is "end of stream", the spec says to prepend the byte (which is end-of-stream) to the stream.  Am I misunderstanding ? If not why are we doing that ?

**Comment by annevk** [comment]
Because it's an error condition we want to return an error and then reprocess the end-of-stream in the Lead byte byte where it'll return finished.

**Comment by mrmixer** [comment]
Thanks.
