### ISSUE TITLE
Additional UTF-8 and UTF-16 labels

### ISSUE THREAD

**Issue by inexorabletash** [whatwg/encoding#168]
Blink and WebKit support these additional aliases for UTF-8 and UTF-16:

UTF-8:
* unicode11utf8
* unicode20utf8
* x-unicode20utf8

UTF-16LE
* csunicode
* ucs-2
* unicode
* iso-10646-ucs-2
* unicodefeff

UTF-16BE
* unicodefffe

(Usable via TextDecoder constructor and the various declarative mechanisms)

The usage is presumably small, but we don't have actual numbers. And I'm lazy. Should we just go ahead and add them?

**Comment by annevk** [comment]
I guess we should, but I'd like to give @hsivonen a chance to weigh in.

**Comment by hsivonen** [comment]
Were these labels from WebKit itself or just things that ICU happened to support? That is, is there some chain of evidence connecting these to the Web?

> csunicode
> iso-10646-ucs-2

These two were UTF-16BE in pre-Encoding Standard Gecko and was restored for Thunderbird 60.4 without evidence of necessity (as a side effect of restoring some email-necessary stuff).

The comments in the [Thunderbird amendments](https://searchfox.org/comm-central/source/mailnews/intl/charsetalias.properties) to encoding labels might be of interest. That list is a mixed bag of ancient Gecko-supported labels that didn't make it to the Encoding Standard plus more recently-added labels motivated by JavaMail and legacy Apple Mail compat. Some of the labels that have been on the list for a long time were motivated by compat with Sun CDE dtmail circa 2002 and Solaris ns_langinfo (at a time when when Gecko put aliases needed for interfacing with OS APIs on the same list as aliases for making sense of data received from the network).

For items other than csunicode and iso-10646-ucs-2, I'd like to see some research into which ones IE supported. Off the top of my head, I think unicode and unicodeFFFE are IE-supported.

I'm not particularly convinced that labels for UTF-16BE and UTF-16LE actually matter, given the BOM. Also, I'm skeptical of the utility of these particular UTF-8 labels. Absent any evidence of usage on the Web, it seems rather ad hoc to add these without adding csutf8 from the IANA.

**Comment by hsivonen** [comment]
> add these without adding csutf8 from the IANA.

We seem to be missing some other cs-prefixed IANA-registered aliases. Where did the cs-prefixed names originate? Has anyone ever actually used them for anything?

**Comment by inexorabletash** [comment]
Not actually answering the above questions, but here's where they manifest in WebKit, which is where Blink inherits them from:

https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/text/TextCodecUTF8.cpp

https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/text/TextCodecUTF16.cpp

I have not chased them further back.

**Comment by annevk** [comment]
I have tests at https://github.com/web-platform-tests/wpt/pull/23427 that match the existing standard, but I'm somewhat inclined to agree that we should support these. What do you think @hsivonen?

**Comment by hsivonen** [comment]
If Blink and WebKit support these, I guess we need to add the labels.
