### ISSUE TITLE
Editorial: change remaining flags to booleans

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#176]
As mentioned at https://github.com/whatwg/encoding/pull/175#discussion_r287275701 this is indeed something that should be done.

The basic process here is:

* Add the ID of the flag `<dfn>` explicitly so that it doesn't change.
* Remove the word "flag" from the `<dfn>` and adjust surrounding wording accordingly to make sense for booleans.
* Ensure "flag" is no longer in the document or only in the non-boolean sense.

**Comment by mulham99** [comment]
> As mentioned at [#175 (comment)](https://github.com/whatwg/encoding/pull/175#discussion_r287275701) this is indeed something that should be done.
> 
> The basic process here is:
> 
> * Add the ID of the flag `<dfn>` explicitly so that it doesn't change.
> * Remove the word "flag" from the `<dfn>` and adjust surrounding wording accordingly to make sense for booleans.
> * Ensure "flag" is no longer in the document or only in the non-boolean sense.
