### ISSUE TITLE
Consider not running the validator on all the encoding tables?

### ISSUE THREAD

**Issue by domenic** [whatwg/encoding#178]
https://travis-ci.org/whatwg/encoding/builds/546617807 is taking a long time and giving a lot of warnings about Unicode normalization forms.

On the other hand, these tables should be valid HTML, I think, so maybe running the validator on them is the right thing to do?

/cc @sideshowbarker

**Comment by sideshowbarker** [comment]
> https://travis-ci.org/whatwg/encoding/builds/546617807 is taking a long time and giving a lot of warnings about Unicode normalization forms.

I can make the checker suppress the warnings. Shall we try that?
