### ISSUE TITLE
Consider removing TextEncoder support for UTF-16

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#18]
AFAICT, non-UTF-8 encoders are exposed in three places in the Web Platform:

1. TextEncoder
2. Query string parsing for URL and the associated APIs
3. Form submission

URL parsing and form submission use UTF-8 when the encoding of the document is either of the UTF-16 encodings, AFAICT, TextEncoder is the only place where the Web Platform exposes UTF-16 encoder functionality.

This is pretty sad, if TextEncoder support UTF-16 just because it can and the support doesn't have strong use cases.

Am I wrong and do proper use cases exist for UTF-16 in TextEncoder to a degree that sets UTF-16 apart from the other legacy encoding that aren't supported in TextEncoder?

**Comment by inexorabletash** [comment]
Since the API is live in Chrome, let me try and get numbers on usage before we consider removing. That may take a release cycle.

**Comment by inexorabletash** [comment]
Early stats (Chrome Canary) show a whopping 0.0000005% of page loads use TextEncoder with UTF-16 variants. I'll report in again once the counter hits stable.

**Comment by peteroupc** [comment]
@inexorabletash : Have you gathered stats on use of UTF-8 with TextEncoder? It's possible that use of UTF-8 in TextEncoder (or TextEncoder in general) might be equally rare.

**Comment by inexorabletash** [comment]
@peteroupc : Good question! Not directly but https://www.chromestatus.com/metrics/feature/timeline/popularity/429 shows the usage of the TextEncoder constructor itself at ~0.0004% of page loads. (So 3 orders of magnitude higher.)

That'd be UTF-8 + UTF-16 + any calls into the constructor that throw due to unsupported encodings. I'm assuming the failure #s due to unsupported encodings are low. https://www.chromestatus.com/metrics/feature/timeline/popularity/430 shows the actual number of calls to `encode()` at 0.0001% of page loads, which puts a lower bound on the successful construction calls. (4x constructions vs. usage calls is a bit odd)

**Comment by annevk** [comment]
@inexorabletash given https://www.chromestatus.com/metrics/feature/timeline/popularity/1061 can we go ahead with this?

**Comment by inexorabletash** [comment]
I'd like the counter to hit the stable channel first. It only went in in December, so it'll be in the M49 release, which should be at the start of March.

That said, it looks extremely promising, even in the internal (absolute, not % numbers).

**Comment by jungshik** [comment]
I wonder if web-based OS such as Chrome/Chromium OS and Firefox OS has any need for UTF-16 encoder. One (edge) use case I can think of is to produce ID3 tag for mp3.

**Comment by annevk** [comment]
@jungshik that also applies to "pure ASCII" or "unaltered iso-8859-1" which we so far have easily resisted to add. Might not hurt to ask though.

**Comment by jungshik** [comment]
Oh. I forgot that ID3 v2.4 supports UTF-8 ( https://en.wikipedia.org/wiki/ID3 ). In that case, my case for UTF-16 encoder with ID3 tag is not valid any more.

**Comment by inexorabletash** [comment]
Counter has hit stable. Usage is around 0.00000000001%. Seems safe to remove.

**Comment by annevk** [comment]
Review of #36 appreciated.

**Comment by inexorabletash** [comment]
Tracking bug for Chrome update: https://crbug.com/595351

**Comment by inexorabletash** [comment]
We'll want to update web-platform-tests as well.

**Comment by Ms2ger** [comment]
https://github.com/w3c/web-platform-tests/issues/2706

**Comment by egoroof** [comment]
> In that case, my case for UTF-16 encoder with ID3 tag is not valid any more.

It is! Windows Explorer and Windows Media Player doesn't support it even in windows 10 (It is the biggest part of OS e.i. all windows over mac and linux). Also it isn't supported by some other players and devices (as I know). That's why I use id3v2.3 in https://github.com/egoroof/browser-id3-writer. And I write strings in utf16. Now I have to use a polyfill instead of native browser API (https://github.com/egoroof/browser-id3-writer/issues/36).

So sad :cry:

**Comment by annevk** [comment]
If your input is a JavaScript string, it should be quite easy to compute UTF-16 bytes. Definitely not something requiring a 100KiB polyfill.

**Comment by egoroof** [comment]
https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding.js it is about 100 KB. But yes, I'll try to write a small polyfill

**Comment by egoroof** [comment]
Omg, it seems I was wrong about it complexity. It is what I was looking for:

```js
function strToUtf16le(str) {
    const utf16 = [];
    const eightBitMask = (1 << 8) - 1;

    for (let i = 0; i < str.length; i++) {
        const charCode = str.charCodeAt(i);
        utf16.push(charCode & eightBitMask);
        utf16.push(charCode >>> 8);
    }
    return utf16;
}
```

**Comment by inexorabletash** [comment]
Assuming the JS strings are UTF-16 (which the API does), then to encode to UTF-16 is just:

```js
function encode_utf16(s, littleEndian) {
  var a = new Uint8Array(s.length * 2), view = new DataView(a.buffer);
  s.split('').forEach(function(c, i) {
    view.setUint16(i * 2, c.charCodeAt(0), littleEndian);
  });
  return a;
}
```

**Comment by egoroof** [comment]
@inexorabletash thanks for this short code! Why don't you use it in your polyfill since now this standart doesn't say anything about encoding steps for utf16?

**Comment by inexorabletash** [comment]
> Why don't you use it in your polyfill since the standart doesn't say anything about encoding steps for utf16?

I just haven't gotten around to updating it, and previously it attempted to match the spec exactly to look for spec bugs. PRs welcome. :)

**Comment by domenic** [comment]
I'm confused. The polyfill should not contain UTF16 encoding, since the spec does not.

**Comment by inexorabletash** [comment]
The polyfill doesn't expose non-UTF-8 encoders by default. But there's a way to opt-in to nonstandard behavior. Further discussion should probably go over in https://github.com/inexorabletash/text-encoding
