### ISSUE TITLE
Export `pushed` concept to ReSpec

### ISSUE THREAD

**Issue by Honry** [whatwg/encoding#180]
For the [`pushed`](https://encoding.spec.whatwg.org/#concept-stream-push) concept, which is not exportable and can not be searched from [ReSpec UI](https://respec.org/xref/).

Could someone help make it exportable? Probably just adding `data-export=""` to the `<dfn>`.

CC / @marcoscaceres

**Comment by marcoscaceres** [comment]
s/ReSpec/Shepherd :)

**Comment by annevk** [comment]
If we want this concept of streams to be reused, it should probably be moved to Infra.

**Comment by ricea** [comment]
I'd definitely like to rename encoding "streams" to "token queues" or something if they're going to be exported, since the confusion with [Streams](https://streams.spec.whatwg.org/) would become unbearable.

**Comment by annevk** [comment]
I'd support that rename happening in Encoding today. I think for exporting adding them to Infra makes the most sense, if they really are a suitable abstraction.

**Comment by andreubotella** [comment]
I'm gonna tackle renaming streams, and exporting it and related terms (end-of-stream, prepended, pushed). Does anyone have anything against the name "token queues"?
