### ISSUE TITLE
What's the correct use of {stream: true} option for Textdecoder.decode

### ISSUE THREAD

**Issue by mko-io** [whatwg/encoding#184]
Just came cross there is a second option can be passed to decoder, My first thought about it is a buffer, so I can do
```javascript
 decoder.decode( new Uint8ArrayBuffer([97, 98, 99]), { stream: true })
```
and append another buffer
```javascript
 decoder.decode( new Uint8ArrayBuffer([100,  101 , 102]), { stream: true })
```
and finally get me a string back which include the 2 parts 
```javascript
 const finalString = decoder.decode( new Uint8ArrayBuffer([]) , { stream: false })
```
but it isn't the case
the first two expression return "abc" and "def" the third give me empty, just like them without the stream option.  and I've tried TextDecoder in Nodejs, it have the same behaviour 

Can anyone can tell me how to use it correctly?

**Comment by ricea** [comment]
The `stream` option changes the handling of the end of the input to allow it to be in the middle of a character. Compare:
```javascript
decoder.decode(new Uint8Array([226, 153]), { stream: true });
// ""
decoder.decode(new Uint8Array([165]), { stream: true });
// "♥"
```
to
```javascript
decoder.decode(new Uint8Array([226, 153]));
// "��"
decoder.decode(new Uint8Array([165]));
// "�"
```
Even with `{stream: true}` the TextDecoder emits all complete characters as soon as possible.

You may find [TextDecoderStream](https://encoding.spec.whatwg.org/#interface-textdecoderstream) a more intuitive way to do the same thing.

**Comment by mko-io** [comment]
@ricea So it's for multi-byte decoding, that make sense and TextDecoderStream is what I'm looking for, hopefully it'll be available soon
