### ISSUE TITLE
Clarify result of division in algorithms

### ISSUE THREAD

**Issue by r12a** [whatwg/encoding#20]
where an algorithm tells you to do something like

```Let lead be pointer / 157 + 0x81. ```

it's not immediately clear that you need to use the floor function, rather than rounding, to bring the result of the division back to an integer.  It would be good to make this clearer in the text.

**Comment by annevk** [comment]
What it does is integer division. Not sure how to best clarify this.

**Comment by domenic** [comment]
floor(pointer / 157) sounds great.

**Comment by r12a** [comment]
yeah, that's basically what i had in mind

**Comment by annevk** [comment]
Would have been cool to use some MathML for the square bracket notation, but that doesn't seem quite ready.
