### ISSUE TITLE
TextDecoder and TextDecoderStream could share more concepts

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#212]
I think the commit that added the streams API only consolidated what was needed to define the shared getters, but it seems to me that they both have a decoder and stream that are of the same type so those could be put on TextDecoderCommon as well.

Not doing this as part of #175 as that's getting rather big already and would be nice if @ricea could confirm.

**Comment by ricea** [comment]
I think the reason I didn't do this was that you can't share the algorithms.
