### ISSUE TITLE
EUC-JP encoding is currently ambiguous

### ISSUE THREAD

**Issue by achristensen07** [whatwg/encoding#225]
Step 7 currently reads as follows:

"Let pointer be the index pointer for code point in index jis0208."

This is ambiguous because there are several code points where there are several pointers to the same code point, such as 0xFA16 has two.  I've observed that Chrome and Firefox always choose the larger of the two.  Strangely, 0xFFE2 has three pointers (137, 8644, and 10736) and Chrome and Firefox use the smallest (137) in this case.  The web platform tests cover these cases.

I was implementing this in https://bugs.webkit.org/show_bug.cgi?id=215970 and noticed these were not specified, so I thought I'd make an issue and see if it's worth making the spec more specific since we are about to have 3 identical implementations.

**Comment by annevk** [comment]
Well, it's not ambiguous if you look at how index pointer is defined:

> The index pointer for code point in index is the first pointer corresponding to code point in index, or null if code point is not in index.

From what you are saying though it sounds like implementations might use the [index Shift_JIS pointer](https://encoding.spec.whatwg.org/#index-shift_jis-pointer) here? Is that also the case for ISO-2022-JP?

cc @hsivonen

**Comment by achristensen07** [comment]
You're right.  It's not ambiguous in most cases, just incorrect.  I think using the index Shift_JIS pointer might fix it (it did in the few cases I checked by hand), but 0xFFE2 would still be ambiguous between using 137 and 10736.  I haven't implemented ISO-2022-JP yet, but I'll let you know when I do.

**Comment by annevk** [comment]
It would not be ambiguous, you'd have to use 137 as it defers to https://encoding.spec.whatwg.org/#index-pointer for the remaining cases.

**Comment by hsivonen** [comment]
> This is ambiguous because there are several code points where there are several pointers to the same code point, such as 0xFA16 has two. I've observed that Chrome and Firefox always choose the larger of the two.

Can you show clearer steps to reproduce for Firefox choosing the larger index for EUC-JP? The larger index values can't even be encoded in the EUC-JP code space.

If I create an EUC-JP document with a form, enter 猪￢ into a form field and submit the form, I see `%FB%A3%A2%CC` in the query string, as the spec requires. With Shift_JIS, I get `%FB%5E%81%CA`, which is also per spec.

(The definition of Shift_JIS pointer excludes the lower copy of IBM kanji from the search. That is, the logic isn't the highest index but the exclusion of a certain range as the behavior of ￢ shows.)

AFAICT, this definitions of "index pointer" and "index Shift_JIS pointer" are not ambiguous.

The test document I used was `data:text/html;charset=EUC-JP,<form action=https://example.com><input name=v><input type=submit></form>` (It appears that GitHub won't linkify it.)

**Comment by achristensen07** [comment]
I had lexically sorted my copy of the table instead of doing a stable sort.  So code points like 0xFA16 which had a pointer greater than 10000 (10934 in this case) and one less than 10000 but greater than 1000 (8462 in this case) were coming first, and I thought I had to choose the last one.  🤦

Having implemented all 3 now, the spec is correct in the pointer choice.

Step 2 of ISO-2022-JP encoder seems to be contrary to the behavior of Chrome and Firefox and soon-to-be WebKit, but that's probably a different issue.

**Comment by hsivonen** [comment]
> Step 2 of ISO-2022-JP encoder seems to be contrary to the behavior of Chrome and Firefox and soon-to-be WebKit, but that's probably a different issue.

I don't see how it is contrary to the Firefox behavior. That step appears to say that if the encoder is already in the ASCII state, there's nothing more to do when the stream ends.

**Comment by achristensen07** [comment]
Oops.  I meant step 3, not step 2.
