### ISSUE TITLE
BufferSource is not specified

### ISSUE THREAD

**Issue by phistuck** [whatwg/encoding#24]
https://encoding.spec.whatwg.org/#textdecoder -
```
USVString decode(optional BufferSource input, optional TextDecodeOptions options);
```
The BufferSource type is not specified anywhere.

ClosureCompiler insists it is Uint8Array -
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540language%2520ECMASCRIPT6_STRICT%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5_STRICT%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%2522use%2520strict%2522%253B%250Aclass%2520Foo%250A%257B%250A%2520constructor()%2520%257B%2520fetch(%2522url%2522).then(response%2520%253D%253E%2520response.arrayBuffer()).then(this.bar)%253B%2520%257D%250A%2520%252F**%2520%2540this%2520undefined%2520%2540param%2520%257BArrayBuffer%257D%2520arrayBuffer%2520*%252F%250A%2520bar(arrayBuffer)%2520%257B%2520console.log(new%2520TextDecoder(%2522utf-8%2522).decode(arrayBuffer))%2520%257D%250A%257D%250A%250Anew%2520Foo()%253B

MDN says it is an ArrayBufferView -
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/decode#Parameters

This should be specified.

Perhaps http://heycam.github.io/webidl/#common-BufferSource (see https://github.com/whatwg/fetch/issues/108).

**Comment by Ms2ger** [comment]
https://heycam.github.io/webidl/#common-BufferSource is the definition. Since you found that, I'm not sure why you claim it's not specified anywhere.

**Comment by phistuck** [comment]
Sorry, I meant, it is not specified within the specification, there is no reference.
(Also, I wrote it before I found it, sorry!)

**Comment by domenic** [comment]
Web IDL types are not referenced. You could make the same complaint about DOMString.

**Comment by phistuck** [comment]
Obviously, I did not.

I did not think about it.
I actually remember searching (and wasting my time) for other similar types as well, so it is too bad that they are not referenced in any specification that is not WebIDL. :(
Thank you and sorry for wasting your time.

**Comment by inexorabletash** [comment]
Coincidentally, I filed https://github.com/google/closure-compiler/issues/1311 a few days ago against ClosureCompiler's issues with Encoding. 

(FWIW, ClosureCompiler apparently does know about BufferSource already, from local testing)

**Comment by inexorabletash** [comment]
I think we can close this, as Encoding does say "This section uses terminology from the DOM and Web IDL."

No worries, @phistuck - I can't count how many times I've also learned that the answer to my question was buried deep in the dark corners of WebIDL.
