### ISSUE TITLE
Talk about instances of decoders and encoders

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#240]
@andreubotella brought this up in #238 and it seems worth addressing, but not as part of that PR. (In particular I don't think it needs to impact a lot of the naming of terms, we just need to add instance in a few places.)

**Comment by andreubotella** [comment]
Looking through the spec, it seems the usages of "decoder" and "decoder instance" are quite inconsistent, and it seems to go against the common mental model, so I'd be up for changing it. The main use case for distinguishing "classes" from instances seems to be that "run" creates a new instance when passed the "class", but it could be passed the encoding and an encode/decode flag instead.

**Comment by annevk** [comment]
I think we should make it so that "run" and "process" always get an instance. Mostly by adding "instance" to wherever we invoke "run" and "process".
