### ISSUE TITLE
Questionable conversion in BOM Sniff

### ISSUE THREAD

**Issue by wlammen** [whatwg/encoding#243]
In section 6.1 under the topic **BOM sniff** I read

> 1. Let BOM be the result of peeking 3 bytes from ioQueue, converted to a byte sequence.

The conversion makes no sense here.  The result of a **peek** is a **list** without **end-of-queue**.  In particular, it is not an **I/O queue** for that reason.  Now **conversions** are only declared if an **I/O queue** is involved, either as a source a destination.  This is for one formally not the case here, since the source is a **list** of bytes and the destination a sequence of bytes. And second a **list** of bytes is already a sequence of bytes, so semantically no conversion is needed at all.

Wolf Lammen

**Comment by annevk** [comment]
I don't think it's the case that an I/O queue has to contain end-of-queue. What part of https://encoding.spec.whatwg.org/#concept-stream made you think that?

**Comment by wlammen** [comment]
> ... Immediate queues have end-of-queue as their last item,
> ...When the underlying network stream closes, an end-of-queue item is to be pushed into the queue. 

I interpret these two sentences such that only unfinished streaming I/O queues may not have a trailing end-of-queue.

**Comment by annevk** [comment]
I see, there are two problems here:

1. Peek returns a list.
2. Instead of converting the list, it tries to convert an I/O queue.

Peek should maybe be changed to always return a byte sequence.

**Comment by andreubotella** [comment]
> Now conversions are only declared if an I/O queue is involved, either as a source a destination.
Formally, yeah, but the idea was to define further conversions in whatwg/infra#319, which would presumably include turning a list of bytes into a byte sequence. This was written in anticipation of that change.

> Instead of converting the list, it tries to convert an I/O queue.
I intended to write that as "let result be (the result of peeking from ioQueue), converted to a byte sequence", not "peeking from (ioQueue, converted to a byte sequence)". Maybe we should clarify.

**Comment by annevk** [comment]
Yeah, I think if we remove the link from "converted" it would be better already.
