### ISSUE TITLE
Add NeXTSTEP encoding

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/encoding#248]
Thread:
https://twitter.com/FakeUnicode/status/1327081558293966848

Mapping:
https://unicode.org/Public/MAPPINGS/VENDORS/NEXT/NEXTSTEP.TXT

Use in the wild:
https://www.w3.org/Proposal.html

More info:
https://en.wikipedia.org/wiki/NeXT_character_set

:upside_down_face:

**Comment by hsivonen** [comment]
Hi, FakeUnicode followers.

The server sends `text/html; charset=iso-8859-1`, so adding this encoding wouldn't fix the page.

I suggest WONTFIX.

**Comment by annevk** [comment]
(To be clear, as a matter of policy we do not add encodings to the list of legacy encodings. Convert legacy things to UTF-8.)
