### ISSUE TITLE
"For logical right shifts operands must have at ..."

### ISSUE THREAD

**Issue by andreubotella** [whatwg/encoding#250]
> For logical right shifts operands must have at least twenty-one bits precision.

Shouldn't this be for left shifts? After all, the result of a logical right shift will never have more bits than the larger of its operands.

**Comment by annevk** [comment]
Hmm, see https://lists.w3.org/Archives/Public/www-international/2014JulSep/0027.html and replies. That might have been wrong though.

**Comment by andreubotella** [comment]
I actually misread that sentence as talking about the result of right shifts, rather than to the operands, which is why I thought it must be referring to left shifts. But although that message is indeed right in that bit shifts do depend on the size of the input, that only makes a difference for logical right shifts of negative numbers:

```
// Arithmetic right shifts
8 (i8) >> 1 = 4
8 (i16) >> 1 = 4
8 (i32) >> 1 = 4
-8 (i8) >> 1 = -4
-8 (i16) >> 1 = -4
-8 (i32) >> 1 = -4

// Logical right shifts
8 (i8) >>> 1 = 4
8 (i16) >>> 1 = 4
8 (i32) >>> 1 = 4
-8 (i8) >>> 1 = 12
-8 (i16) >>> 1 = 32764
-8 (i32) >>> 1 = 2147483644
```

And since the only right shifts in the standard have code points or code units as their input, they must be positive.

**Comment by annevk** [comment]
Okay, I would be fine dropping that sentence. I've been kinda hoping we can remove the majority of that section once https://github.com/whatwg/infra/issues/87 is sorted.

**Comment by andreubotella** [comment]
Closing this in the meantime, then.
