### ISSUE TITLE
What's the correct choice for BIG5 F9FE?

### ISSUE THREAD

**Issue by lygstate** [whatwg/encoding#28]
According to:
https://lists.w3.org/Archives/Public/public-whatwg-archive/2012Apr/0095.html
The decoding for F9FE from different vendor are different,
And the `whatwg encoding` standard are choose
`F9FE ` -> `U+FFED`, is that the correct behavior ?
Because from the vendor's point of view, U+2593 is a better option
```
> F9FE =>
> opera-hk: U+FFED
> firefox: U+2593
> chrome: U+2593
> firefox-hk: U+2593
> opera: U+2593
> chrome-hk: U+FFED
> internetexplorer: U+2593
> windows-os: U+2593
> hkscs-2008: <U+FFED>
```

**Comment by annevk** [comment]
If you read the rest of that thread it seems pretty clear why @foolip stuck with HKSCS in https://lists.w3.org/Archives/Public/public-whatwg-archive/2012Apr/0136.html. @r12a you might want to test this.

@lygstate is this behavior problematic for you somewhere?

**Comment by foolip** [comment]
I think that both C6CD and F9FE boil down to sticking with HKSCS-2008 unless there's a problem in not doing so.

Note that since that thread, both Firefox and Chrome have changed. I don't know when it happened, but both now map F9FE to U+FFED for both the Big5 and Big5-HKSCS labels. Tested with ad-hoc local files on this form:
```HTML
<!DOCTYPE html>
<meta charset=Big5>
<h1>F9FE (the actual bytes, created with hexedit)
```

**Comment by lygstate** [comment]
@annevk I've just noticed the differences between cp950 from Unicode.org vs Big5 from this encoding standard, so I just post here for decided answer.

**Comment by annevk** [comment]
I see. Closing this then since we decided on this behavior back in 2012 and there has been no reason to revisit.
