### ISSUE TITLE
7-bit ASCII encoding

### ISSUE THREAD

**Issue by janschejbal** [whatwg/encoding#287]
I couldn't find any encoding that only decodes ASCII bytes (i.e. 0x00-0x7F), and am slightly surprised that "ascii" maps to windows-1252.

Would it still make sense to add an encoding like "7bit" which only supports encoding/decoding 7-bit ASCII characters? The intended use case would be decoding data that is expected to be 7-bit ASCII, likely typically used with fatal=true.

**Comment by annevk** [comment]
This suggestion as well as "true latin1" (or isomorphic decode/encode as per Infra) have come up from time-to-time. Thus far we haven't acted on them as they:

* lack good use cases;
* can be written in JavaScript directly without much hassle; and
* they are not a part of the web platform's current text encoding infrastructure and we don't want to expand that as new things ought to use UTF-8 exclusively.

**Comment by janschejbal** [comment]
Thanks, sounds reasonable - you're right that the check can be implemented relatively easily. Should we close this as wontfix to document the decision?

**Comment by annevk** [comment]
Sounds good, thanks for confirming you agree!
