### ISSUE TITLE
Introduce "output encoding"

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#29]
@hsivonen pointed out that when HTML ends up using e.g., the "replacement" encoding to encode something, we would want to label that as `utf-8`, not `replacement`. Therefore, we should introduce a new concept called "output encoding" that is the encoding itself except for `replacement` (and soon hopefully utf-16le/be).

Then we remove replacement's encoder. Make sure the encode hook uses the output encoding of an encoding. And make sure HTML and URL use the encode hook correctly.

**Comment by hsivonen** [comment]
> encoding itself except for replacement (and soon hopefully utf-16le/be).

I'm looking for a concept that _today_ is the encoding itself except utf-8 for replacement, utf-16le and utf-16be. That is, in form submission and URL query parsing, we'd define that you go through this new concept and then encode according to the encoding you got through this new concept.

**Comment by annevk** [comment]
Ah yeah, thank you for mentioning that. Hopefully it's still not weird that we'd remove replacement's encoder.

We'd also have to make sure that until the `TextEncoder` issue around utf-16 is resolved, that does still use utf-16 encoders.

**Comment by annevk** [comment]
@hsivonen could you please review #35? Thank you!
