### ISSUE TITLE
Creating test suites for each encoding.

### ISSUE THREAD

**Issue by lygstate** [whatwg/encoding#30]
For example:
test-big5.txt
test-big5.utf8.txt
And the test-big5.txt just contains all the valid characters in BIG5 encoding.

test-big5.invalid.txt
test-big5.invalid.utf8.txt
And test-big5.invalid.txt
 contains invalid characters in text along with valid characters
The file test-big5.invalid.utf8.txt would contains the corresponding valid characters.

**Comment by annevk** [comment]
As the README notes the tests are located elsewhere. We might want to mention @r12a's tests too since they're not yet part of web-platform-tests it seems.

**Comment by r12a** [comment]
i do intend to add them to web-platform-tests at some point (they should be ready to go, just need to go through the process of moving them). In the meantime, you can find them at:

https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en

https://www.w3.org/International/tests/repo/results/encoding-dbl-byte-labels.en

https://www.w3.org/International/tests/repo/results/encoding-sb-dec

(All of the above are linked from https://www.w3.org/International/tests/#encoding-spec)

Click on the links in the left-most column to see the actual tests. (You'll get to a framework which allows you to view any test in a group that typically corresponds with each of the results pages above.)

You can also generate a list of all characters in an encoding using http://r12a.github.io/apps/encodings/. Look for the control "Show all the characters in this encoding" towards the bottom of the page.

**Comment by r12a** [comment]
@annevk now we have some pretty good test coverage and results, we need to bring the attention of the implementers to the areas where there are gaps. What's the best way to do that?  Raise issues here?

**Comment by annevk** [comment]
@r12a if all implementations disagree with the specification an issue here would be good since we might have to change the specification. Otherwise bugs on individual implementations is probably better. We could use an issue, perhaps even this one, for triage, if you want. What you did before by posting to www-international also seemed to have worked well.

**Comment by lygstate** [comment]
Create testsuite here would ensure maximal implementation compatibility.

**Comment by Ms2ger** [comment]
On the contrary, having a separate test suite outside of wpt is an excellent way of getting it ignored by browser vendors.

**Comment by annevk** [comment]
Closing this since this is already handled by wpt. @r12a, always happy to chat if things are still unclear. Let me know.

**Comment by r12a** [comment]
pushed other stuff aside to upload a first set of tests to wpt
https://github.com/w3c/web-platform-tests/pull/3027

results from last time i ran them are available at 
https://www.w3.org/International/tests/repo/results/encoding-dbl-byte.en
i'll try to make some time to check whether the results need updating
