### ISSUE TITLE
SHIFT_JISX0213 are not supported.

### ISSUE THREAD

**Issue by lygstate** [whatwg/encoding#31]

**Comment by vyv03354** [comment]
There is no reason to add a new non-utf-8 encoding at all.
We (Japanese) have had enough Shift_JIS variants. As a Gecko Internationalization peer, I will not add support such an encoding even if by any chance it is added to the spec.

**Comment by lygstate** [comment]
@vyv03354 You are a Japanese

**Comment by vyv03354** [comment]
Yes. As a Japanese user, I will never proliferate even more Japanese encoding variants. It will only add confusion. I strongly discourage to add the encoding.

Minor nits: SHIFT_JISX0213 is obsolete and superseded by Shift_JIS-2004. But again, I will not add any new non-UTF-8 encodings in the first place.

**Comment by lygstate** [comment]
@vyv03354  It's seems that you didn't figure out the relationship between SHIFT_JISX0213 & Shift_JIS-2004, indeed, I means JISX0213 & Shift_JIS-2004

**Comment by lygstate** [comment]
It's seems the Japanese encoding standards are totally a mess, the standard committee's specifications are now followed and updated frequently.
http://www.asahi-net.or.jp/~ax2s-kmtn/ref/index.html

**Comment by annevk** [comment]
@lygstate what is your justification for this request?

**Comment by annevk** [comment]
Closing since this lacks justification and there is no implementer interest.
