### ISSUE TITLE
Consider making the DOM name the canonical name

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#32]
It's pretty sad that this specification chose to invent a new case (the lower case) for canonical names when a historical casing (the IANA case implemented by WebKit/Blink and, except for gbk, by Gecko) already existed.

Imagine that you are writing a library for this stuff. You can't compute the DOM name from the name in this specification without hard-coding knowledge of the DOM names. However, you could compute the name in this specification by ASCII-lower-casing the DOM name.

Is there a good reason not to:

1. Change the _names_ in this specification to the _Compatibility names_ from the DOM spec.
2. Get rid of the special mapping in the DOM spec.
3. Define that `.encoding` of `TextEncoder` and `TextDecoder` returns _name_ (i.e. now the mixed-case IANA/DOM name) ASCII-lowercased.

?

**Comment by annevk** [comment]
I don't think so. I mostly did it to keep the weird casing out of other potential future uses, but those should probably not exist since there's utf-8. (Note that it's not 100% IANA casing. E.g., `GB18030` is `gb18030` in DOM.)

**Comment by hsivonen** [comment]
> potential future uses, but those should probably not exist since there's utf-8.

Indeed.

> (Note that it's not 100% IANA casing

Good point. Not only `GB18030` vs. `gb18030` but also `ibm866` vs. `IBM866`. Now I really wonder where WebKit got its casing from. Did they copy Gecko after all but failed to copy `gbk`?

Anyway, I still think the concept _name_ should directly be what's currently the DOM _compatibility name_.

**Comment by inexorabletash** [comment]
Sounds fine to me. This is what Blink's impl does internally already. We may want to leave a note in the spec that the concept name casing is odd because of compatibility and is referenced in other standards, given that it's pretty subtle.

**Comment by vyv03354** [comment]
> This is what Blink's impl does internally already.

Same for Gecko's impl.

**Comment by annevk** [comment]
@hsivonen `IBM866` is `IBM866` per IANA.
