### ISSUE TITLE
Ambiguous wording in GB18030 decoder

### ISSUE THREAD

**Issue by stasoid** [whatwg/encoding#325]
### What is the issue with the Encoding Standard?

I am struggling to understand what "Prepend *gb18030 second* followed by *byte* to ioQueue" exactly means in [gb18030 decoder](https://encoding.spec.whatwg.org/#gb18030-decoder) step 4.2.

Does it mean to prepend a sequence containing *gb18030 second* and *byte* or does it mean first prepend *gb18030 second*, then prepend *byte*? This is the only place where this wording is used in the context of "prepend". All the other usages of "prepend" are unambiguous.

As a side note, I propose to entirely get rid of the concept of prepending a sequence. It is used only in one place, in step 5.5 of [utf-16-decoder](https://encoding.spec.whatwg.org/#shared-utf-16-decoder), and it only clutters understanding. It would be much clearer to just say "if *UTF-16BE decoder* is true prepend *byte2*, then prepend *byte1*, otherwise, prepend *byte1*, then prepend *byte2*". The note just above [4. Encodings](https://encoding.spec.whatwg.org/#encodings) says that "prepend operation is an internal detail of the algorithms in this specification, and is not to be used by other standards", so it looks safe to remove this concept.

**Comment by annevk** [comment]
It means to prepend a sequence. Otherwise you'd reorder which is never done.

Getting rid of sequences seems fine. If you're able to sign https://participate.whatwg.org/agreement you could contribute a patch if you're willing.

cc @andreubotella

**Comment by annevk** [comment]
Yeah, it's meant to "restore" _ioQueue_ as if those bytes were not processed after all, allowing them to be processed anew with the main difference that we now know there's an error of sorts.

**Comment by stasoid** [comment]
I see now, thank you.
