### ISSUE TITLE
Reference link wrong in "If ioQueue is empty..."

### ISSUE THREAD

**Issue by Explorer09** [whatwg/encoding#329]
### What is the issue with the Encoding Standard?

Section 3 "Terminology" of the Encoding Standard of WHATWG (https://encoding.spec.whatwg.org/)

> To read an item from an I/O queue ioQueue, run these steps:
> 1. If ioQueue is empty, then wait until its size is at least 1.
> 2. [...]

The term "empty" on the text "If ioQueue is empty" referenced the wrong item in the Infra Standard:
(https://infra.spec.whatwg.org/#list-empty)

It should be: (https://infra.spec.whatwg.org/#list-is-empty)

That's it.

**Comment by annevk** [comment]
Thank you!
