### ISSUE TITLE
Replacement encoding should handle empty input better

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#33]
See https://twitter.com/hsivonen/status/691585344769282048 by @hsivonen and @zcorpan.

**Comment by hsivonen** [comment]
One reason to do this:
Avoiding the weird case of reporting zero previous bytes as the cause of error. E.g. here https://github.com/hsivonen/encoding-rs/blob/1dac008e4610d1ff4e2e59fe33aa460c59f0f215/src/lib.rs#L1188

**Comment by annevk** [comment]
I left the final step "return finished" in place. I could have removed that with this change as it's not technically observable. Would you prefer that?
