### ISSUE TITLE
utf-8 decoder lead byte switch branches 0xE0 to 0xEF, 0xF0 to 0xF4 need 'return continue'

### ISSUE THREAD

**Issue by inexorabletash** [whatwg/encoding#42]
https://github.com/whatwg/encoding/pull/38 changed how the lead byte is processed. It removed "Then (byte is in the range 0xC2 to 0xF4, inclusive) set UTF-8 code point to UTF-8 code point << (6 × UTF-8 bytes needed) and return continue."

The first two and final switch branches (0x00 to 0x7F, 0xC2 to 0xDF, and Otherwse) have returns, but the remaining two (0xE0 to 0xEF, 0xF0 to 0xF4) do not, so fall through to the trail byte processing.

Looks like they just need additional "Return continue" substeps added

**Comment by annevk** [comment]
You mean decoder, right?

Oh, I thought that was intentional on @hsivonen's part. I should have checked more carefully.

Should we add "return continue" explicitly everywhere or put it in a paragraph after the `<dl>`? I guess everywhere is a little clearer, though more verbose.

**Comment by inexorabletash** [comment]
Oops, yes, decoder. 

I have no preference as to where the return(s) should go. One at the end seems fine.

**Comment by inexorabletash** [comment]
Are we waiting for @hsivonen to comment? Should I put up a PR? (might have cycles this week)

**Comment by annevk** [comment]
I think I was, but he doesn't have much time so we should probably just fix it. I can do it tomorrow.

**Comment by hsivonen** [comment]
Sorry about the delay and sorry about deleting "return continue". Indeed, after processing a valid lead byte, the algorithm should return continue.
