### ISSUE TITLE
Please double-check the end of the EUDC range

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#53]
In the Shift_JIS decoder, the *inclusive* end pointer 10528 looks suspicious, since it means only one possible trail byte (the lowest possible) is allowed for the lead byte F9. One would expect either the special case to run to the end of the pointers whose lead byte is F8 (making 10528 an *exclusive* bound) or run to the end of the pointers whose lead byte is F9.

Please double-check that the range is correct and, if it is, please add a note saying that the range is weird on purpose.

cc @vyv03354

**Comment by annevk** [comment]
This range originated from https://www.w3.org/Bugs/Public/show_bug.cgi?id=24130. @vyv03354 can probably clear this up.

**Comment by vyv03354** [comment]
The entire F9 range is valid as the removed commit indicates:
https://github.com/whatwg/encoding/commit/651f672ee988702da03f56ad8bdfda00b51a21ea
This is a bug of the current decoder algorithm.

**Comment by annevk** [comment]
Okay, so it should be 10715 ((0xF9 - 0xC1) x 188 + 0xFC - 0x41 in decimal)?

**Comment by annevk** [comment]
@r12a not sure if you test this range, but you might have to update a few things here.

**Comment by vyv03354** [comment]
> Okay, so it should be 10715 ((0xF9 - 0xC1) x 188 + 0xFC - 0x41 in decimal)?

I think so.

**Comment by annevk** [comment]
So https://github.com/whatwg/encoding/commit/236196e8ce274c44ab45109dfc8da9539ae44e1d introduced the current range and it seems I just made an error there by not including the full range of 0xF9.

**Comment by annevk** [comment]
Thanks @vyv03354 for the help and @hsivonen for spotting this!

**Comment by r12a** [comment]
@annevk i updated the js file that does the decoding for the sjis tests. The results were the same.
