### ISSUE TITLE
Add "replacement" as a label for the replacement encoding

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#70]
I've written "The name of an encoding is also one of its labels, except in the case of the replacement encoding whose name is not one of its labels." inconveniently many times when either [documenting code that implements the Encoding Standard](https://hsivonen.fi/rs/encoding_rs/struct.Encoding.html) or when [otherwise explaining the concepts](https://bugzilla.mozilla.org/show_bug.cgi?id=1191841#c15).

Also, I've written code that does something like "if input string is 'replacement', don't run _get an encoding_, otherwise, run _get an encoding_" when working with [interfaces](https://dxr.mozilla.org/mozilla-central/source/intl/uconv/nsScriptableUConv.cpp#270) [that](https://dxr.mozilla.org/mozilla-central/source/netwerk/base/nsUnicharStreamLoader.cpp#177) [were](https://dxr.mozilla.org/mozilla-central/source/netwerk/base/nsStandardURL.cpp#221) [designed](https://hg.mozilla.org/integration/mozilla-inbound/rev/e07157e29deedd1b2bda60c62f307503c558844f) (four links there, but GitHub's styling makes it unobvious) before there was clarity of what strings are _labels_ and what strings are _names_ used where an enum value or a reference to a singleton object representing an encoding would be more appropriate software design (when those interfaces potentially have callers in add-ons that I can't fix).

All this would become simpler if _get an encoding_ for the _name_ of an encoding always returned the encoding itself. However, it's kinda sad to expose another Web-exposed label just to make implementing and explaining stuff easier, so I'm not sure if I should request this.

But at least this deserves some discussion.

**Comment by domenic** [comment]
/cc @cdumez who I noticed recently updated WebKit's encoding labels in https://github.com/WebKit/webkit/commit/f203fd07772753d2f73dcce865664a943dc6e4ff

I assume it would be a bad option to rename "replacement" to something like, say, "csiso2022kr"?

**Comment by cdumez** [comment]
@domenic Despite having done the update in WebKit recently, I am actually not familiar with this area enough to comment. I know that we do have the "replacement" label for the replacement encoding in WebKit though.

**Comment by hsivonen** [comment]
> I know that we do have the "replacement" label for the replacement encoding in WebKit though.

Are you sure? [Testing](http://logs.glob.uno/?c=freenode%23whatwg&s=24+Aug+2016&e=24+Aug+2016#c1003829) indicates otherwise.

**Comment by hsivonen** [comment]
> I assume it would be a bad option to rename "replacement" to something like, say, "csiso2022kr"?

That would be pretty confusing, so I think that's a bad option.

**Comment by cdumez** [comment]
@hsivonen: I wrote the patch very recently so you would need to try a WebKit nightly build.

**Comment by annevk** [comment]
@cdumez someone did try a nightly. It appears that WebKit (per spec and other browsers) does not alias "replacement" to the behavior of the replacement encoding.

**Comment by cdumez** [comment]
Oh my bad, there was some last minute review feedback on my patch and it appears it killed the replacement alias. Sorry about the bad information.

**Comment by annevk** [comment]
We added replacement in https://www.w3.org/Bugs/Public/show_bug.cgi?id=21057. I don't think we really discussed adding it as a label before. I'm certainly open to adding it as it does simplify the system a little bit, but also not a whole lot.

@jungshik thoughts?

**Comment by inexorabletash** [comment]
FWIW, I concur with the OP - frequent special cases in the code and tests, but sad about adding it to the web just to make implementations cleaner. So no vote either way.

**Comment by annevk** [comment]
I'm going to close this since everyone is on the fence. Feel free to reopen though if you feel strongly since it doesn't seem like it would be a hard sell.

**Comment by annevk** [comment]
I'm going to reopen this to add "replacement" as a label as the special cases apparently continue to cause problems (at least in Gecko while integrating encoding-rs) for no real gain.

As nobody objected and @hsivonen now favors this approach I hope that is acceptable, but I'll leave some time for feedback just in case.

**Comment by annevk** [comment]
I'm surprised this is such a big deal in code as there's nothing in the standard (or any standards that use this standard) to my knowledge that trips over this.

Nevertheless, I created the PR, review appreciated. Note that before landing it I should probably:

1. Update tests.
2. File bugs against Firefox, WebKit, and Chromium. Not sure about Edge as they haven't made an effort to comply thus far I think.

**Comment by domenic** [comment]
Shouldn't we get another implementation interested before landing?

**Comment by annevk** [comment]
I considered @inexorabletash's reply above as such, but happy to wait for something more explicit.

**Comment by inexorabletash** [comment]
It involves deleting code on our side so I'm okay with the change.

**Comment by inexorabletash** [comment]
FWIW, I put up a Blink change: https://chromium-review.googlesource.com/c/559973/ - I'll wait for test updates to hit WPT and roll into Blink, though. 

Sanity check: we would now expect an HTML file with `<meta http-equiv="content-type" content="text/html; charset=replacement">` to render as &#xFFFD; yes?

**Comment by annevk** [comment]
@inexorabletash yeah, that wouldn't be any different from it saying iso-2022-kr or some such. Note that it would have to appear within the first 1024 bytes.

@hsivonen do you want to review the change?

**Comment by annevk** [comment]
Bugs:

* https://bugs.webkit.org/show_bug.cgi?id=174577
* https://github.com/hsivonen/encoding_rs/issues/22
* https://bugs.chromium.org/p/chromium/issues/detail?id=744405

To my knowledge Edge hasn't made an effort yet so I'm not including them for now.

**Comment by domenic** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard/ lists them as "In Development" so they might appreciate a bug.

**Comment by inexorabletash** [comment]
FYI, Blink change landed. 

Worth noting: @annevk's WPT changes didn't trip any failures when rolled into Blink's CI since the tests currently exercise the encoding labels via the API, and replacement encodings already threw just like unknown labels.

We've got [blink-specific tests that use XHR and data: URLs to verify various encodings](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/encoding/char-decoding.html?q=char-decoding.html&sq=package:chromium&l=147) and specifically that the replacement ones yield U+FFFD. I was lame and just added "replacement" to the list. We should probably tidy up and upstream those (among other fun cases like UTF-7).

**Comment by annevk** [comment]
@inexorabletash yeah, that would be great.

Filed https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12808940/ against Edge.
