### ISSUE TITLE
Confusion between KOI8-U and KOI8-RU encodings

### ISSUE THREAD

**Issue by bhaible** [whatwg/encoding#74]
The current draft maps the labels "koi8-u" and "koi8-ru" to a single encoding, and the mapping table that it uses (index-koi8-u.txt) does not match either of the widely used mapping tables for KOI8-U and KOI8-RU.

In detail:

Glibc and other software consider KOI8-U and KOI8-RU to be different.
KOI8-U was defined through an RFC, see https://en.wikipedia.org/wiki/KOI8-U.
KOI8-RU was defined through a draft RFC that was never finalized, see https://www.terena.org/activities/multiling/koi8-ru/

The mapping in index-koi8-u.txt differs from the common KOI8-U mapping at the positions 0xAE, 0xBE.

The mapping in index-koi8-u.txt differs from the common KOI8-RU mapping at the positions 0x93, 0x96..0x99, 0x9B..0x9D, 0x9F.

For details about the mapping tables, see
http://haible.de/bruno/charsets/conversion-tables/index.html
http://haible.de/bruno/charsets/conversion-tables/KOI8-U.html
http://haible.de/bruno/charsets/conversion-tables/KOI8-RU.html

Do you have data about who actually uses KOI8-U and KOI8-RU and how?
Is it necessary to deal with these two encodings at all?

**Comment by annevk** [comment]
See the discussion in https://www.w3.org/Bugs/Public/show_bug.cgi?id=17053.

**Comment by bhaible** [comment]
> See the discussion in https://www.w3.org/Bugs/Public/show_bug.cgi?id=17053.

The main argument I can see this in this discussion is "IE takes the labels koi8-u and koi8-ru to mean KOI8-RU and not KOI8-U."

It amounts to the question: Which of Internet Explorer and Mozilla is more used with KOI8-U and KOI8-RU?

**Comment by annevk** [comment]
Historically, most likely IE given the market dominance it had.

**Comment by annevk** [comment]
Given that we already discussed this and nobody cared enough to gather data back then, closing this. I don't think we'll end up wiser this time around.
