### ISSUE TITLE
Editorial style nits

### ISSUE THREAD

**Issue by domenic** [whatwg/encoding#76]
Class names like Uint8Array, ArrayBuffer, TypeError, and RangeError should link to their definitions.

For associated "internal slots" (e.g. encoding, error mode, ignore BOM flag, etc.), their defining instance should be a `<dfn>`, and all subsequent uses of or references to them should be `<a>`s. Currently both are `<b>`.

**Comment by annevk** [comment]
I don't see why those class names are different from DOMString. They're all defined by IDL.

**Comment by domenic** [comment]
Agreed, DOMString should get linked too.

**Comment by annevk** [comment]
Is there a Bikeshed issue on this? That should basically get this fixed.

**Comment by annevk** [comment]
There's actually parts I could fix, but not the cross-referencing from IDL blocks.

**Comment by annevk** [comment]
And the internal slot parts also still need to be fixed.

**Comment by annevk** [comment]
If USVString really needs to be linked that would require an issue against Bikeshed itself. Everything else should be taken care off now. Thanks!
