### ISSUE TITLE
Inform readers about the structure of the sparsity of index-euc-kr

### ISSUE THREAD

**Issue by hsivonen** [whatwg/encoding#78]
index-euc-kr is rather sparse. That is, it has a lot of pointer space without corresponding characters.

To avoid making implementors ship bloated software and to avoid making implementors to work out the pattern of the index holes on their own, it would be courteous to add an informative note about the pattern of the holes in the index.

These holes are easier to see in [bestfit949.txt](http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WindowsBestFit/bestfit949.txt).

Visually (I haven't verified programmatically), when lead is 0xC7 or greater, only trail bytes 0xA1...0xFE (inclusive) map to characters using only 94 slots of the 190 in each stride. When lead is less than 0xC7, trail bytes 0x5B...0x60 (inclusive) and 0x7B...0x80 (inclusive) are not used using only up to 178 slots of 190 in each stride.

Some strides (leads in the range 0xA2...0xAF) have even fewer than 178 slots used, but I haven't yet worked out if there's a pattern to those.

**Comment by jungshik** [comment]
> Some strides (leads in the range 0xA2...0xAF) have even fewer than 178 slots used, but I haven't yet worked out if there's a pattern to those.

The holes for those lead ranges come from tho holes in KS X 1001 (rows 2 ~ 15). So, don't expect any pattern there. A few holes there have been used to add characters to KS X 1001. For instance, row 2 - cells 70 ~ 72 were assigned new characters, Euro sign, Registered mark sign and Korean postal code sign U+327E when KS X 1001 was revised. See https://goo.gl/aIfPPq .

**Comment by annevk** [comment]
Why is that called a stride?

Currently all indexes require this to be found out to some extent by implementers. The encoder/decoder algorithms have some hits about the ranges in play (or hard limits, if you will), but no detailed information geared in that direction.

I'm not opposed to adding it, given that it's unlikely we're tweaking these indexes (much) going forward, but it would be good to know where you would expect that information and how valuable it would be for me to put effort into finding it out. (I don't recall from memory unfortunately.)

**Comment by ricea** [comment]
Drive-by comment: I favour putting this information in a separate "optimisation" section. It's not necessary for implementors. If you're trying to verify the correctness of an existing implementation you don't need it all. But if you're aiming to write a high-quality implementation from scratch it's nice to have all this information in one place.

Random aside: A neat trick for finding undocumented patterns is to convert the table into an image and look at it by eye.

**Comment by hsivonen** [comment]
> Why is that called a stride?

It seemed confusing to call it a row, because the pre-Unicode CJK standards, KS X 1001 included, use a 94 by 94 grid, where a "row" is 94 cells wide. Since EUC-KR lead minus offset gets multiplied by something other than 94, it seemed bad to say "row". I used "stride" by analogy with the notion of [how many bytes a pixel row takes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa473780(v=vs.85).aspx) even if it isn't fully filled with visible pixels.

I'm not aware of "stride" being standard character encoding terminology and am OK with another word as long as it's not too easy to mix up with "rows" in the original standards.

**Comment by hsivonen** [comment]
> Currently all indexes require this to be found out to some extent by implementers.

I agree in general, but the EUC-KR case is unusual in there being holes throughout the index _and_ the holes having a pattern.

**Comment by annevk** [comment]
We used to have a less sparse index until I opted for simplicity in https://www.w3.org/Bugs/Public/show_bug.cgi?id=16691. 4b20cf61260ed00357663755886d9f7617d60b35 suggests that originally we had this pairing of bytes and then mapped that to pointers:

Lead: 0x81 to 0xC6
Trail: 0x41 to 0x5A, 0x61 to 0x7A, 0x81 to 0xFE

Lead: 0xC7 to 0xFE
Trail: 0xA1 to 0xFE

Perhaps we should indicate for multi-byte encodings what constitute (potentially) valid byte patterns?

**Comment by inexorabletash** [comment]
As a tangent from the comment by @ricea &mdash; at one point I came across very nice visual depictions of how various text encodings divvy up the lead/trail byte space to map to the indexes. The only thing I can dig up now is http://lfw.org/text/jp.html which covers some of the Japanese encodings in graphical form.

(No objection to non-normative comments, although I worry more about developers using older libraries that didn't pick up late additions to various encodings than from-scratch implementations. Huge respect for @hsivonen of course!)

**Comment by r12a** [comment]
@inexorabletash there are a largeish number of nice diagrams of the type you mention in Ken Lunde's CJKV Information Processing book.  Is that what you were thinking of?

**Comment by hsivonen** [comment]
> My hypothesis is that the extended areas are even sorted in Unicode order, but I haven't verified that, yet.

They are. Both in the additional Hangul EUC-KR and the additional Unified Ideographs in gb18030.

Additionally, the original KS X 1001 Hangul block is also in Unicode order.

As for resolution of this issue, I suggest the following:

* Including the visualizations I created (or something similar) as informative material next to the spec ("next to" in the sense the txt files are next to the spec but not pasted into the spec itself). (If this is editorially OK as an idea, I can ask Gerv about CC0ing the script I wrote. The fonts I used are all under OFL 1.1.)

* Adding informative notes containing the the observations above about the Unicode ordering of the three Hangul blocks and the top and left Unified Ideograph blocks in gb18030.

* Noting that the three Hangul block taken together cover all of Hangul in Unicode.

* Noting that the Unified Ideograph blocks in gb18030 taken together cover all of the CJK Unified Ideographs block in Unicode.

* Adding notes about the relationship between Unicode order and the order of Level 2 Hanzi in gb18030 (the block whose top left corner is on row 0x2F column 0x60 in the visualization) and Level 2 Kanji in jis0208 (pointers from 4418 to 7801, inclusive). I haven't really figured out what exactly to say here. Level 2 Hanzi seems mostly Unicode-ordered but not quite. I haven't had time to examine whether Level 2 Kanji is Unicode-ordered but according to Lunde it is ordered first by radical and then by stroke like Unified Ideographs in Unicode.

**Comment by annevk** [comment]
I like the idea of hosting the index visualizations and I'm on board with your suggestions. However, I would appreciate it if you could write the PR since I suspect it would be way easier for you to do at this time. One thing that needs to be addressed with the index visualizations I think is that we also include the color coding in a different way. Perhaps by including information in the title attribute?

**Comment by hsivonen** [comment]
> I like the idea of hosting the index visualizations and I'm on board with your suggestions.

Cool.

> However, I would appreciate it if you could write the PR since I suspect it would be way easier for you to do at this time.

I'll work on a PR.

Is it OK to check in the fonts? In a fonts/ directory maybe? Should I check in the output .html files? It seems that the other generated files are checked in. Should I use a subdirectory?

> One thing that needs to be addressed with the index visualizations I think is that we also include the color coding in a different way. Perhaps by including information in the title attribute?

So far, I've used the visualizations to aid better implementations of gb18030, euc-kr and euc-jp jis0208 decode. At this point, I'm going to take a break to redo the visualizations without the tooltips before I finish the Japanese encodings, and I wish I'd have stopped to do that sooner. Having to hover the cells to see the code point and pointer values is bad.

So I'd prefer a solution that doesn't involve the title attribute.

What problem are you trying to solve by introducing redundancy for color? Color blindness or also blindness? For color blindness, I wonder if there's a set of suitable set of distinguishable colors that works with the known variants of color blindness. (I'm too uninformed about the topic to know whether that's possible.) If some non-color indicators are added, I'd like to use something that doesn't get exported to the clipboard if you select multiple cells and copy them to the clipboard.

For completely non-visual use, there are more potential problems to solve: For example, you might want a screen reader to read the numbers in the language of the user, but the language of the HTML is declared to whatever optimizes Firefox font selection if you've turned Web Fonts off.

**Comment by annevk** [comment]
Logistics:

* Now we use Travis it might be possible to check in less of the output. The *.txt resources are somewhat special however as I only regenerate those when there is a change and that affects the date they display (which is mostly non-normative given the hash, but seems bad to update all the time).
* If the fonts are generally applicable a better place might be https://github.com/whatwg/resources.whatwg.org.
* A subdirectory seems okay. Again, with Travis and deploying through scp that should be less of an issue now than it used to be.

Accessibility: I was thinking about blind users, though colorblindness matters too of course. I didn't realize you (ab)used language to optimize font selection. I also have no great suggestions here, since these tables are rather involved. Perhaps something to ask stackoverflow/Twitter?

**Comment by hsivonen** [comment]
The PR addresses everything except the order of Level 2 Hanzi in gb18030 and Level 2 Kanji in jis0208. (Neither is perfectly Unicode-ordered.)
