### ISSUE TITLE
Commit snapshots

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#80]
@domenic if we issue commit snapshots for the Encoding Standard, I guess ideally we also snapshot all the text and JSON resources, even though they are going to be mostly static.

It seems fairly easy to just copy those resources into the commit/branch directory. The hyperlinks in the source are already path-relative so that should work fine.

Thoughts?

**Comment by domenic** [comment]
Yeah, it sounds pretty easy. Just insert some `cp` lines appropriately into the script. Remember you can use `--local` to test locally.

**Comment by annevk** [comment]
d3c768806223b8df9a8d5c942adb11c11e5aaff4 fixed this and I forgot to reference this issue from it, not that it matters much. It does indeed all seem to work nicely, although there's a little more copypasta than I'd like.
