### ISSUE TITLE
[HTML], [URL], and [XML] should probably be informative references

### ISSUE THREAD

**Issue by domenic** [whatwg/encoding#86]
They only appear in notes.

[DOM] is only normative because of the use of the term "context object", I guess?

**Comment by annevk** [comment]
Yeah, I used to also rely on DOM for ASCII lowercase and such I think.

[UNICODE] usage also seems only non-normative, though I guess through [INFRA] it is normative...

**Comment by annevk** [comment]
It doesn't seem we use context object here so I guess I should remove DOM.
