### ISSUE TITLE
Non-browser versus JavaScript

### ISSUE THREAD

**Issue by annevk** [whatwg/encoding#87]
Currently we state "Non-browser user agents are not required to support this API."

I wonder if we should phrase that differently somehow to be inclusive of other JavaScript deployments, such as Node.js. @jasnell thoughts? I'm guessing Node.js has its own encoding libraries, but maybe this is another place where we can pursue convergence.

**Comment by jasnell** [comment]
I've been thinking about this also. There has been at least some interest expressed from users in having consistency but Node.js does already have encoding support already for the basics (limited to UTF-8, UTF-16le, Latin-1 and ASCII). I'll take a todo to investigate a bit further into what we can possibly do here.

**Comment by jcranmer** [comment]
The one comment I would make is that other contexts are more likely to want to support encoding to legacy charsets. If the goal is convergence, then there would need to be some discussion of how to handle encoding characters not present in the target charset.

(Note that I'm not asking that web browsers implement support for such encoding processes).

**Comment by hsivonen** [comment]
I think it's good for Node.js to expose browser-compatible interfaces and to some extent it's probably good to consider Node.js when deciding things that could go either way on browsers but one way is clearly preferable on Node.js, but I think it's a somewhat slippery slope in terms of scope creep for the WHATWG to officially start considering non-Web client software to be in scope.

I'm particularly worried about an increase in stated scope resulting in a) requests to expose non-UTF-8 encoders (see the previous comment) and this spilling over to browsers and b) requests to add encodings for non-Web client use cases and this spilling over to browsers.

**Comment by jasnell** [comment]
One great thing about Node.js here is it's very intentional approach to not growing in scope needlessly. Support for legacy encodings beyond the quite limited set already supported by core would be a darn near impossible sell in core and would be expected to be provided by userland instead. Even implementing this basic interface is likely to meet with some resistance but I do plan to try.

**Comment by annevk** [comment]
I guess the main problem here is the inconsistency across standards. URL for instance says nothing about its API.

Ideally I'd want all JavaScript environments to expose this and at a minimum it needs to be all browsers. Maybe we should just state something like that. And say that other programming languages are probably best to adopt an API that suits their needs best.

(And yes, I don't think we'd expand scope either way. Optional features make a poor standard.)
