### ISSUE TITLE
"decoder = TextDecoder(encoding)"

### ISSUE THREAD

**Issue by ricea** [whatwg/encoding#90]
https://encoding.spec.whatwg.org/commit-snapshots/7696b7abf42ac13ccb59f183ee4e9e836ade13c2/#example-end-of-stream

> decoder =​ TextDecoder\(encoding\)

Missing "new" statement?

**Comment by inexorabletash** [comment]
Oops, yes. (This worked in Firefox many moons ago.)

**Comment by annevk** [comment]
Thanks, found a couple other things worth fixing too.
